"""Render a hand-authored ReAct-style agent trace as a vertical timeline.

The trace itself is real structured data (authored below, not generated by
an actual LLM call) for a plausible task: "find the year a named research
paper was published, using a search tool, and summarize the finding." It
includes a failed tool call (search tool times out) followed by a retry with
a narrowed query, so the figure shows both the normal loop and a recovery
branch -- the two things worth seeing in a trace that a flowchart of the
*abstract* agent loop can't show.
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _theme import apply_theme, savefig, CATEGORICAL, INK, INK_SECONDARY, MUTED, GRIDLINE

import textwrap
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch

# step: (type, short label, detail text)
# types: thought, tool_call, tool_result, tool_error, final_answer
trace = [
    (1, "thought", "Reasoning",
     "Need the publication year of the paper 'Attention Is All You Need'. "
     "I don't know it precisely -- call the search tool."),
    (2, "tool_call", "search(query=\"Attention Is All You Need paper year\")",
     "Structured call: {\"tool\": \"search\", \"args\": {\"query\": \"...\"}}"),
    (3, "tool_error", "search: timeout after 8s",
     "Upstream search API did not respond in time."),
    (4, "thought", "Reasoning",
     "Tool call failed, not a dead end. Retry once with a narrower, more "
     "specific query before giving up on this step."),
    (5, "tool_call", "search(query=\"Attention Is All You Need arXiv\")",
     "Narrowed query, same tool."),
    (6, "tool_result", "search -> \"arXiv:1706.03762, submitted Jun 2017\"",
     "Result returned: title, arXiv id, submission date."),
    (7, "thought", "Reasoning",
     "Result gives a submission date, not a venue-published date. Good "
     "enough to answer the user's actual question -- no further calls needed."),
    (8, "final_answer", "Final answer",
     "\"Attention Is All You Need\" was released on arXiv in June 2017 "
     "(arXiv:1706.03762)."),
]

TYPE_STYLE = {
    "thought": (CATEGORICAL[6], "thought"),
    "tool_call": (CATEGORICAL[0], "tool call"),
    "tool_result": (CATEGORICAL[2], "tool result"),
    "tool_error": (CATEGORICAL[7], "tool error"),
    "final_answer": (CATEGORICAL[5], "final answer"),
}

apply_theme()
n = len(trace)
step_gap = 1.55
fig, ax = plt.subplots(figsize=(9.8, 1.05 * n + 1.2))

y_positions = [step_gap * (n - i) for i in range(n)]
x_lane = 0.0
x_text = 0.55

for (step, kind, label, detail), y in zip(trace, y_positions):
    color, kind_label = TYPE_STYLE[kind]

    # Node on the timeline.
    ax.scatter([x_lane], [y], s=270, color=color, zorder=3, edgecolor="white", linewidth=1.2)
    ax.text(x_lane, y, str(step), ha="center", va="center", fontsize=9,
             color="white", fontweight="bold", zorder=4)

    # Kind tag, then step label, then wrapped detail -- reads top to bottom
    # in the same order the agent actually produced it.
    ax.text(x_text, y + 0.30, kind_label.upper(), ha="left", va="center", fontsize=8,
             color=color, fontweight="bold")
    ax.text(x_text, y + 0.05, label, ha="left", va="center", fontsize=10.5,
             color=INK, fontweight="600")
    wrapped = textwrap.fill(detail, width=70)
    ax.text(x_text, y - 0.24, wrapped, ha="left", va="top", fontsize=8.7,
             color=INK_SECONDARY, linespacing=1.4)

# Connecting spine.
ax.plot([x_lane, x_lane], [min(y_positions) - 0.4, max(y_positions) + 0.4],
         color=GRIDLINE, linewidth=2.2, zorder=1)

# Highlight the retry branch: dashed side-arrow from the error node back to
# the next thought node, and from that thought to the retried tool call.
err_y = y_positions[2]   # step 3, tool_error
retry_thought_y = y_positions[3]  # step 4
retry_call_y = y_positions[4]     # step 5

arrow = FancyArrowPatch(
    (x_lane - 0.32, err_y - 0.08), (x_lane - 0.32, retry_thought_y + 0.08),
    connectionstyle="arc3,rad=-0.4", arrowstyle="-|>", mutation_scale=14,
    color=CATEGORICAL[7], linewidth=1.6, linestyle=(0, (4, 2)), zorder=2,
)
ax.add_patch(arrow)
ax.text(x_lane - 0.7, (err_y + retry_thought_y) / 2, "retry",
        ha="center", va="center", fontsize=8.5, color=CATEGORICAL[7],
        fontweight="bold", rotation=90)

# Bracket marking the whole recover-and-retry span.
ax.plot([x_lane - 1.05, x_lane - 1.05], [retry_call_y - 0.5, err_y + 0.5],
         color=MUTED, linewidth=1, linestyle=":")
ax.text(x_lane - 1.22, (err_y + retry_call_y) / 2, "recovers from\ntool failure",
        ha="right", va="center", fontsize=8, color=MUTED, style="italic")

ax.set_xlim(-2.2, 8.2)
ax.set_ylim(min(y_positions) - 1.1, max(y_positions) + 1.1)
ax.set_xticks([])
ax.set_yticks([])
for spine in ax.spines.values():
    spine.set_visible(False)
ax.grid(False)

ax.set_title(
    "A ReAct-style agent trace: task = \"find and summarize a fact using a search tool\"",
    fontsize=12.5, color=INK, pad=14,
)

# Legend of step types.
handles = [plt.Line2D([0], [0], marker="o", linestyle="", color=c, markersize=9,
                       markeredgecolor="white", label=lbl)
           for c, lbl in TYPE_STYLE.values()]
ax.legend(handles=handles, loc="upper right", fontsize=8.5, ncol=1,
          bbox_to_anchor=(1.0, 1.0))

out = Path(__file__).resolve().parents[2] / "docs" / "images" / "agents_trace_timeline.png"
savefig(fig, str(out))
